enabled_worlds: []
disabled_commands: []

# If a player logs out while in combat, they will be banned
ban_on_log: false

# Plugin will automatically search for updates (from dev.bukkit.org) and download them if found
# Occurs during server startup
auto_update: false